### ISSUE TITLE
This plugin also fires for non Azure DEVOPS

### ISSUE THREAD

**Issue by Grueslayer** [cedarbaum/fugitive-azure-devops.vim#1]
This plugin always returns an url for any given file.

You can reproduce this by cloning a remote repository (e.g. from github) and disabling vim-rhubarb. If you try to use
```:Gbrowse``` it tries to open an url without the host information (you can see it in the ```:messages```. You need (at least) return an empty string in ```azuredevops#homepage_for_remote``` if the file url does not match (which results in a correct error message from fugitive not finding any matching handler).

**Comment by cedarbaum** [comment]
Sorry for the very late reply. This should be fixed in 05d680f95fff1f7bed7bc34e811c72ae9492da61. Thanks for reporting the issue!
