### ISSUE TITLE
Double encoded URLs

### ISSUE THREAD

**Issue by Willem-J-an** [cedarbaum/fugitive-azure-devops.vim#4]
Hi!

The plugin is not really working for me, because it appears spaces in the project name are double encoded and end up like %2520.

**Comment by cedarbaum** [comment]
Sorry about the late reply - can you please provide an example project name that causes this issue? I've tried to reproduce it with a project called "Test Project" and `GBrowse` seems to work in this case.

**Comment by Willem-J-an** [comment]
I suppose the extension draws from the git remote endpoints. They look like this:
```
git remote -v
origin  git@ssh.dev.azure.com:v3/organization/Project%20With%20SPACES%20SAD/MyRepository (push)
```

Hope that helps!

**Comment by cedarbaum** [comment]
I tested this by plugging it into an existing unit test (https://github.com/cedarbaum/fugitive-azure-devops.vim/blob/master/tests/gbrowse.vader#L16) and it does seem to correctly escape the spaces. A few follow-ups:

- Confirm you're using the latest versions of this plugin as well as `fugitive.vim`. There were some changes in `fugitive.vim` for handling character escapes a while back.
- Clone the public repo https://dev.azure.com/scedarbaum/Test%20project/_git/Test%20project and try using `GBrowse`. Is there the same issue?
- Provide the exact context you're using `GBrowse` in. For example, are you browsing a specific file when this happens? If so, what's the path? Ideally, we could write a test that reproduces this - see here for all the scenarios currently being tested: https://github.com/cedarbaum/fugitive-azure-devops.vim/blob/master/tests/gbrowse.vade

**Comment by cedarbaum** [comment]
Hey @Willem-J-an, haven't heard back in a while, so am going to close this for now. If you go  through the above steps and are still seeing issues, please feel free to reopen and we can continue debugging.
